/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { GeneratePresignedUrlDtoResponse } from '../models';
import {
  GeneratePresignedUrlDtoResponseFromJSON,
  GeneratePresignedUrlDtoResponseToJSON,
} from '../models';

/**
 *
 */
export class GeneratePresignedUrlControllerApi extends runtime.BaseAPI {
  /**
   */
  async getPresignedUrlRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<GeneratePresignedUrlDtoResponse>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/v1/generate-presigned-url`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      GeneratePresignedUrlDtoResponseFromJSON(jsonValue)
    );
  }

  /**
   */
  async getPresignedUrl(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<GeneratePresignedUrlDtoResponse> {
    const response = await this.getPresignedUrlRaw(initOverrides);
    return await response.value();
  }
}
