/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  LectureRankingDtoResponse,
} from '../models';
import {
    LectureRankingDtoResponseFromJSON,
    LectureRankingDtoResponseToJSON,
} from '../models';

/**
 * 
 */
export class RankingControllerApi extends runtime.BaseAPI {

    /**
     */
    async getRankingRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<LectureRankingDtoResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/ranking`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => LectureRankingDtoResponseFromJSON(jsonValue));
    }

    /**
     */
    async getRanking(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<LectureRankingDtoResponse> {
        const response = await this.getRankingRaw(initOverrides);
        return await response.value();
    }

}
