/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LectureDtoRateHelpfulness
 */
export interface LectureDtoRateHelpfulness {
    /**
     * 
     * @type {number}
     * @memberof LectureDtoRateHelpfulness
     */
    helpfulnessRating: number;
}

/**
 * Check if a given object implements the LectureDtoRateHelpfulness interface.
 */
export function instanceOfLectureDtoRateHelpfulness(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "helpfulnessRating" in value;

    return isInstance;
}

export function LectureDtoRateHelpfulnessFromJSON(json: any): LectureDtoRateHelpfulness {
    return LectureDtoRateHelpfulnessFromJSONTyped(json, false);
}

export function LectureDtoRateHelpfulnessFromJSONTyped(json: any, ignoreDiscriminator: boolean): LectureDtoRateHelpfulness {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'helpfulnessRating': json['helpfulnessRating'],
    };
}

export function LectureDtoRateHelpfulnessToJSON(value?: LectureDtoRateHelpfulness | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'helpfulnessRating': value.helpfulnessRating,
    };
}

