/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface LectureDtoRequest
 */
export interface LectureDtoRequest {
  /**
   *
   * @type {number}
   * @memberof LectureDtoRequest
   */
  topicId: number;
  /**
   *
   * @type {string}
   * @memberof LectureDtoRequest
   */
  audioUrl: string;
}

/**
 * Check if a given object implements the LectureDtoRequest interface.
 */
export function instanceOfLectureDtoRequest(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'topicId' in value;
  isInstance = isInstance && 'audioUrl' in value;

  return isInstance;
}

export function LectureDtoRequestFromJSON(json: any): LectureDtoRequest {
  return LectureDtoRequestFromJSONTyped(json, false);
}

export function LectureDtoRequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): LectureDtoRequest {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    topicId: json['topicId'],
    audioUrl: json['audioUrl'],
  };
}

export function LectureDtoRequestToJSON(value?: LectureDtoRequest | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    topicId: value.topicId,
    audioUrl: value.audioUrl,
  };
}
