/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 *
 * @export
 * @interface UserDtoMe
 */
export interface UserDtoMe {
  /**
   *
   * @type {string}
   * @memberof UserDtoMe
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof UserDtoMe
   */
  authToken: string;
}

/**
 * Check if a given object implements the UserDtoMe interface.
 */
export function instanceOfUserDtoMe(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && 'name' in value;
  isInstance = isInstance && 'authToken' in value;

  return isInstance;
}

export function UserDtoMeFromJSON(json: any): UserDtoMe {
  return UserDtoMeFromJSONTyped(json, false);
}

export function UserDtoMeFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDtoMe {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json['name'],
    authToken: json['authToken'],
  };
}

export function UserDtoMeToJSON(value?: UserDtoMe | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
    authToken: value.authToken,
  };
}
